### ISSUE TITLE
Do you have any other algorithm implementations on Gemini?

### ISSUE THREAD

**Issue by yumh** [thu-pacman/GeminiGraph#13]
I wanted to implement a k-core algorithm on Gemini but I found it very difficult. I pray you to help me. Do you have any other algorithm implementations on Gemini? Can you send it to me？

**Comment by coolerzxw** [comment]
Hi. I think you can first have a look at the implementations of other algorithms in Ligra as the programming interfaces are similar.

**Comment by yumh** [comment]
Thank you
