### ISSUE TITLE
Error result  while performing BFS algorithm

### ISSUE THREAD

**Issue by yumh** [thu-pacman/GeminiGraph#14]
Error result  while performing BFS algorithm.
Input data :# nodes:  3997962 ===> output : found_vertices = 1655427. 
Input data :# nodes:  2394385 ===> output : found_vertices = 1
Why is the number of input nodes  inconsistent with the number of output nodes?

**Comment by coolerzxw** [comment]
I am not sure I fully understand what you mean. Can your give more details?

**Comment by yumh** [comment]
[root@hw073 GeminiGraph]# ./toolkits/bfs     /home/renrui/graph-datasets/data/email-EuAll.txt.bin  **265214**   1
active(0)>=1
active(1)>=129372
active(2)>=19139
active(3)>=6
exec_time=0.014675(s)
**found_vertices = 148518**

**Comment by coolerzxw** [comment]
Well, the found_vertices in the output of BFS is the number of vertices that can be reached from the root vertex, which doesn't necessarily equal |V|.
