### ISSUE TITLE
Stealing part is missing

### ISSUE THREAD

**Issue by lushl9301** [thu-pacman/GeminiGraph#16]
https://github.com/thu-pacman/GeminiGraph/blob/170e7d36794fdcaca077f23bd0cd76e8ccab9e74/core/graph.hpp#L1847-L1848

Hi Xiaowei,
I notice that the stealing operation is missing in the line mentioned above.
I wonder if the possible reason is since this part of the code is using pull-based operation, so task stealing could only have minor effects?

Thanks

**Comment by lushl9301** [comment]
https://github.com/thu-pacman/GeminiGraph/blob/170e7d36794fdcaca077f23bd0cd76e8ccab9e74/core/graph.hpp#L1327-L1330

One more question, since ```tuned_chunks_sparse``` is no in-use. The ```transpose()``` and ```tune_chunks()``` operations seem redundant? Only the last ```tune_chunks``` help to generate ```tuned_chunks_dense```, which is used in the dense edge processing right?

**Comment by coolerzxw** [comment]
@lushl9301 Yes you are right, work-stealing is not taking effect here (though the work done in dense_slot is less than that in dense_signal, so the effect is minor as you suggested)... Regarding your second question, some applications like Betweenness Centrality need to transpose the graph, so `tuned_chunks_sparse` will be used in those cases.

**Comment by lushl9301** [comment]
thanks for your clarification.
