### ISSUE TITLE
Match paper with code

### ISSUE THREAD

**Issue by larrywong98** [thu-pacman/GeminiGraph#17]
Could you help me find where the code corresponds to the picture(Dual mode CSR and CSC representation)?
![Screenshot_1](https://user-images.githubusercontent.com/54010526/75315799-ad12f800-589e-11ea-8201-665fb9617475.png)
@coolerzxw

**Comment by coolerzxw** [comment]
https://github.com/thu-pacman/GeminiGraph/blob/170e7d36794fdcaca077f23bd0cd76e8ccab9e74/core/graph.hpp#L120-L130
The variables shown in the above region are related with edge representation in Gemini. You may lookup these variables to get into the details.

@larrywong98

**Comment by larrywong98** [comment]
Thanks!
