### ISSUE TITLE
Distributed algorithm segmentation fault (using SLURM + MVAPICH2)

### ISSUE THREAD

**Issue by sunrise2575** [thu-pacman/GeminiGraph#5]
Hi,

I'm using **MVAPICH 2.3b** and **SLURM 17.11.4**
(with MUNGE, MariaDB, OpenSSL, PAM, etc....) on CentOS 7.4

I use three nodes. (Intel Xeon CPU cluster)
sun07 is the master, which has _slurmctld_ and _slurmd_ daemon process,
and sun08, sun09 are slaves, which only have _slurmd_ daemon process.

MVAPICH compiling & installing was conducted by
`./configure --with-pmi=pmi2 --with-pm=slurm`
as mentioned on the MVAPICH2 manual.
(http://mvapich.cse.ohio-state.edu/static/media/mvapich/mvapich2-2.3b-userguide.pdf)

I tested linux command **_hostname_** and **_mpi_hello.c_**.
(https://computing.llnl.gov/tutorials/mpi/samples/C/mpi_hello.c)

```
[heeyong@sun07 ~] srun -n 3 hostname
srun: job88 queued and waiting for resources
srun: job88 has been allocated resources
sun07
sun08
sun09
```

```
[heeyong@sun07 ~] srun -n 3 ./mpi_hello
srun: job 89 queued and waiting for resources
srun: job 89 has been allocated resources
Hello from task 0 on sun07!
MASTER: Number of MPI tasks is: 3
Hello from task 2 on sun09!
Hello from task 1 on sun08!
```
Those two tests were perfectly worked in multi-node situation.

However, If I run command like this:

```
[heeyong@sun07 gemini]$ srun -n 3 ./toolkits/pagerank /path/to/twitter-2010.binedgelist 41652230 20
srun: job 95 queued and waiting for resources
srun: job 95 has been allocated resources
[sun09:mpi_rank_2][error_sighandler] Caught error: Segmentation fault (signal 11)
srun: error: sun09: task 2: Segmentation fault (core dumped)
srun: error: sun08: task 1: Segmentation fault (core dumped)

```

and no response anymore.

I'm sure that I clearly compiled and executed Gemini on the same MVAPICH version,
like you mentioned at https://github.com/thu-pacman/GeminiGraph/issues/2

Finally, I traced manually (using printf) and
I found that the program stucks at 1082~1102 line of **core/graph.hpp**

What is the problem...?

**Comment by coolerzxw** [comment]
Hi @sunrise2575 , is the input file properly encoded in the binary edge list format (i.e. each edge containing two integers in binary)? By the way, you can first try running the program using a single process (i.e. without "srun -n [N]") and see if it behaves normally.

**Comment by coolerzxw** [comment]
"By using top, I figured out that after showing segmentation fault,
it constantly uses exactly 2 cores with 100% utilization ... per each node."
According to the above behavior and your MPI environment being MVAPICH2, I think the problem might be that [MPI_Init_thread(argc, argv, MPI_THREAD_MULTIPLE, &provided)](https://github.com/thu-pacman/GeminiGraph/blob/master/core/mpi.hpp#L55) does not return MPI_THREAD_MULTIPLE as required. You can try passing "MV2_ENABLE_AFFINITY=0" to run the command (i.e. before srun) according to [this discussion](http://mailman.cse.ohio-state.edu/pipermail/mvapich-discuss/2013-October/004616.html).

**Comment by sunrise2575** [comment]
MV2_ENABLE_AFFINITY=0 solved the whole problem. Thanks so much!
